/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ean.edu;

import com.j256.ormlite.dao.Dao;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.jdbc.JdbcConnectionSource;
import com.j256.ormlite.support.ConnectionSource;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JGamboa
 */
public class FrameAgregarEmpleado extends javax.swing.JFrame {
    //Atributos
    Dao<Empleados, Integer> tablaEmpleados = null;
    
    /**
     * Creates new form FrameAgregarEmpleado
     */
    public FrameAgregarEmpleado(){
        try {
            initComponents();
            
            //Crear la tabla
            String urlBD = "jdbc:sqlite:data/nomina.db";
            
            //Crear conexion
            ConnectionSource fuente = new JdbcConnectionSource(urlBD);
            
            //Crear DAO
            tablaEmpleados = DaoManager.createDao(fuente, Empleados.class);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cedulaLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        salarioLabel = new javax.swing.JLabel();
        ced = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        car = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        agregarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmp = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NOMINA");

        cedulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaLabel.setText("Cedula:");

        nombreLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombreLabel.setText("Nombre:");

        cargoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargoLabel.setText("Cargo:");

        salarioLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salarioLabel.setText("Salario:");

        ced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedActionPerformed(evt);
            }
        });

        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });

        agregarBtn.setText("Agregar Empleado");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        listaEmp.setEditable(false);
        listaEmp.setColumns(20);
        listaEmp.setRows(5);
        jScrollPane1.setViewportView(listaEmp);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("EMPLEADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaLabel)
                            .addComponent(nombreLabel)
                            .addComponent(cargoLabel)
                            .addComponent(salarioLabel)
                            .addComponent(agregarBtn))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salirBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ced, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(nom)
                                .addComponent(car)
                                .addComponent(sal)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel2)
                        .addContainerGap(208, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedulaLabel)
                            .addComponent(ced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargoLabel)
                            .addComponent(car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salarioLabel)
                            .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarBtn)
                            .addComponent(salirBtn))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        int cedula = Integer.parseInt(ced.getText().trim());
        String nombre = nom.getText().toUpperCase();
        String cargo = car.getText().toUpperCase();
        int salario = Integer.parseInt(sal.getText().trim());
        
        Empleados emp = new Empleados(cedula, nombre, cargo, salario);
        try {
            if (existeEmpleado(cedula)){
                JOptionPane.showMessageDialog(null, "Error: Cedula ya existe!");
        }
            else{
        tablaEmpleados.create(emp);
        JOptionPane.showMessageDialog(null, "Empleado creado!");
        mostrarEmpleados();
            }
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mostrarEmpleados();
    }//GEN-LAST:event_formWindowActivated
      
    private boolean existeEmpleado(int ced) throws SQLException{
    Empleados c  = tablaEmpleados.queryForId(ced);
    if (c != null){
        return true;
    }
    return false;
    
    }
    
    
    private void mostrarEmpleados(){
        try {
            List<Empleados> empleados = tablaEmpleados.queryForAll();
            
            listaEmp.setText(String.format("%-10s %10s %10s %20s\n",
                    "CEDULA", "NOMBRE", "CONTACTO", "SALARIO"));
            for(Empleados e: empleados){
            listaEmp.append(String.format("%-10d %10s %10s %20s\n",
                    e.getCedula(),
                    e.getNombre(),
                    e.getCargo(),
                    e.getSalario()));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAgregarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTextField car;
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JTextField ced;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listaEmp;
    private javax.swing.JTextField nom;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField sal;
    private javax.swing.JLabel salarioLabel;
    private javax.swing.JButton salirBtn;
    // End of variables declaration//GEN-END:variables
}
